version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tempomente?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db
    networks:
      - planejador-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tempomente
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - planejador-network

volumes:
  mysql-data:

networks:
  planejador-network:
    driver: bridge 