version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-planejador:3306/tempomente?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SERVER_PORT=9090
      - JWT_SECRET=minhachavesecretaProducao123456789012345678901234567890
    depends_on:
      - mysql-planejador
    networks:
      - planejador-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.planejamento.rule=Host(`planejamento.leonardogeja.com.br`)"
      - "traefik.http.services.planejamento.loadbalancer.server.port=9090"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS,HEAD"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors.headers.accessControlMaxAge=3600"
      - "traefik.http.middlewares.cors.headers.addVaryHeader=true"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=false"
      - "traefik.http.middlewares.cors.headers.accessControlExposeHeaders=Authorization"
      - "traefik.http.routers.planejamento.middlewares=cors"
      - "traefik.http.routers.planejamento.entrypoints=web"
      - "traefik.http.routers.planejamento.service=planejamento"

  mysql-planejador:
    image: mysql:8.0
    container_name: mysql-planejador
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tempomente
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - planejador-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:

networks:
  planejador-network:
    driver: bridge
